# The set of config parameters for the simulation platform.
# See src/types.hpp for detailed definitions.

# We use Hong Kong as our case study.
area_config: 
  lon_min: 113.75
  lon_max: 114.50
  lat_min: 22.10
  lat_max: 22.60
mod_system_config:
  fleet_config:
    fleet_size: 5
    veh_capacity: 2
    initial_lon: 114.18
    initial_lat: 22.30 
  request_config:
    max_dispatch_wait_time_s: 60
    max_pickup_wait_time_s: 600
simulation_config:
  cycle_s: 60.0
  simulation_duration_s: 120
  warmup_duration_s: 0
  winddown_duration_s: 0
