# The set of config parameters for the simulation platform.
# See src/types.hpp for detailed definitions.

# We use Manhattan as our case study.
data_file_path:
  osrm: "../osrm/map/manhattan.osrm"
  vehicle_station: "./datalog/map-data/stations-101.csv"
  taxi_data: "./datalog/taxi-data/manhattan-taxi-20160525.bin"
area_config: 
  lon_min: -74.0300
  lon_max: -73.9030
  lat_min: 40.6950
  lat_max: 40.8825
mod_system_config:
  fleet_config:
    fleet_size: 5
    veh_capacity: 4
    initial_lon: -74.009115
    initial_lat: 40.71692
  request_config:
    request_density: 0.1
    max_pickup_wait_time_s: 600
simulation_config:
  simulation_start_time: "2015-05-25 00:00:00"
  cycle_s: 20
  warmup_duration_s: 0
  simulation_duration_s: 100
  winddown_duration_s: 0
output_config:
  datalog_config:
    output_datalog: true
    path_to_output_datalog: "./datalog/demo.yml"
  video_config:
    render_video: true
    path_to_output_video: "./media/demo.mp4"
    frames_per_cycle: 2  # total frames = simulation_duration_s / (cycle_s / frames_per_cycle)
    replay_speed: 100  # fps = replay_speed / (cycle_s / frames_per_cycle)
